# Generated by Django 2.0.3 on 2018-03-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertreemodel',
            old_name='forest_newick',
            new_name='forest_newicks',
        ),
    ]
