# Generated by Django 2.0.3 on 2018-03-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='supertree',
        ),
        migrations.DeleteModel(
            name='Supertree',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
