# Generated by Django 2.0.3 on 2018-03-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertree',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='pub_date',
        ),
    ]
