# Generated by Django 2.0.3 on 2018-03-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='supertree',
        ),
        migrations.DeleteModel(
            name='Supertree',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
