# Generated by Django 2.0.3 on 2018-03-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180323_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trees',
            new_name='Tree',
        ),
    ]
