# Generated by Django 2.0.3 on 2018-03-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180323_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='supertree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Supertree'),
        ),
    ]
